version: '3.8'

services:
  posts:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=posts-service
    networks:
      - microservices-network
    volumes:
      # Mount source code for development hot reload
      - ./src:/app/src
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:4000/posts',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - event-bus

  # Event bus service (if running together)
  event-bus:
    build:
      context: ../event-bus
      dockerfile: Dockerfile
    ports:
      - '4005:4005'
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=event-bus
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:4005/events',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  microservices-network:
    driver: bridge

volumes:
  posts-data:
